### ISSUE TITLE
"no such file or directory"

### ISSUE THREAD

**Issue by haodong** [holyshawn/overture#11]
I've set these three variable properly "IPNetworkFilePath", "DomainFilePath", "HostsFile" in config file. But neither relative path nor absolute path is working.

```
ERRO[0000] Open IP network file failed: open : no such file or directory
ERRO[0000] Open Custom domain file failed: open : no such file or directory
...
INFO[0000] Load hosts file failed: 0xc420074f90
```

**Comment by freeyoung** [comment]
From version `1.3.0`, the directives `IPNetworkFilePath` and `DomainFilePath` have been renamed to `IPNetworkFile` and `DomainFile`. Please update your config file accordingly.

**Comment by haodong** [comment]
Now it works great!
Thanks for explaining~
