### ISSUE TITLE
What's the unit of timeout?

### ISSUE THREAD

**Issue by haodong** [holyshawn/overture#12]
Is it a "second" ?
If so, wouldn't it be so long for the default value to be 6 seconds?

**Comment by holyshawn** [comment]
This timeout is a cumulative timeout for dial, write and read, overrides DialTimeout, ReadTimeout and WriteTimeout when non-zero, and the default value of those three is 2.
https://godoc.org/github.com/miekg/dns

**Comment by haodong** [comment]
I got it. Thanks!
