### ISSUE TITLE
Add SOCKS5 proxy support for TCP upstream

### ISSUE THREAD

**Issue by madeye** [holyshawn/overture#14]
Hi Holyshawn,

As suggested here https://github.com/shadowsocks/shadowsocks-org/issues/52#issuecomment-281669753, it seems we can replace the old ChinaDNS with this project.

I'm wondering if it's possible to add SOCKS5 proxy support for TCP upstream. If so, we can directly integrate overture to many shadowsocks projects, like shadowsocks-android and go-shadowsocks2.

Thanks,
Max

**Comment by solarhell** [comment]
SGTM.

**Comment by madeye** [comment]
I found some comments may be useful: https://github.com/miekg/dns/pull/247#issuecomment-131732420

**Comment by holyshawn** [comment]
It's a good idea, but why not use another program and communicate with it by socket? @madeye

**Comment by madeye** [comment]
@holyshawn Do you mean talking to overture from shadowsocks? For the proposal from @riobard, I think it's doable.

But currently, we just want to replace PDNSD/ChinaDNS/ss-tunnel with one overture...

**Comment by riobard** [comment]
@madeye I think @holyshawn meant that you can now use overture and as-tunnel to do remote resolution without adding SOCKS5 support to overture itself.

**Comment by holyshawn** [comment]
@madeye I mean perhaps we can make each program do one thing well. And ss-tunnel is a great program for avoiding DNS pollution, we can just use its ip and port.

**Comment by madeye** [comment]
Hmm, actually it's feature request for shadowsocks-android, where we are using ss-tunnel to setup tunnels to upstream DNS servers. However, the problem is if we want to use multiple upstreams, we have to start multiple ss-tunnel...

So, it'd be very useful to have SOCKS5 proxy support, then we can use overture with ss-local (only one instance required).

**Comment by holyshawn** [comment]
Got it. Multiple upstreams socks5 proxy support is quiet necessary.

**Comment by maddie** [comment]
I have implemented SOCKS5 proxy support in overture and tested ok, I have added two options in `config.json`: `UseSOCKS5Proxy` and `SOCKS5Proxy` for enabling the functionality and proxy address respectively.

Is it OK to assume that once this option is enabled, all queries that goes via TCP will go through the proxy? If so I will submit a pull request for review.

**Comment by holyshawn** [comment]
@madeye Thank you for your work. Hmm, I write some code too yesterday and I have finished it now, you may check my update. I think every DNS upstream has its own socks5 configuration would be better, and the other revision you do I will review later.

**Comment by madeye** [comment]
Hmm, I think the pull request is from @maddie, not from me @madeye. 😃

**Comment by madeye** [comment]
Thanks for change! Closing the issue.

**Comment by holyshawn** [comment]
@maddie @madeye Oh, there is something wrong......

**Comment by maddie** [comment]
@holyshawn There isn't much other changes, I have only renamed `hostsfile` directory to `hosts` and made amendments to README
