### ISSUE TITLE
不能正常解析域名

### ISSUE THREAD

**Issue by rwzsycwan** [holyshawn/overture#3]
gfwlist里的域名v4、v6解析正常，不在列表里的不能正常解析，报Get dns response failed: Response message is nil, maybe timeout 错误。
配置文件：
{
  "BindAddress": ":5353",
  "PrimaryDNSAddress": "119.29.29.29:53",
  "PrimaryDNSProtocol": "udp",
  "AlternativeDNSAddress": "127.0.0.1:1053",
  "AlternativeDNSProtocol": "tcp",
  "Timeout": 6,
  "RedirectIPv6Record": true,
  "IPNetworkFilePath": "/tmp/china_ip_list.txt",
  "DomainFilePath": "/tmp/gfwlist.txt",
  "DomainBase64Decode": true,
  "MinimumTTL": 6000,
  "EDNSClientSubnetPolicy": "auto",
  "EDNSClientSubnetIP": ""
}。
还有，能不能设置多个上游服务器？哪个先返回用哪个。

**Comment by holyshawn** [comment]
是实际使用无法解析还是 dig 无法解析，一次还是多次，已知存在在打开EDNSClientSubnet的时候 debian 8 下的 dig 会报这个错误的 bug，而我用 osx 完全没有这个问题。。。
多个上游考虑过，日后会跟进。

**Comment by rwzsycwan** [comment]
哦，我用的是debian8下的dig，看来是这个问题。
