### ISSUE TITLE
Domestic DNS resolution timeout with EDNSClientSubnetPolicy set to 'auto' and DNSPod as primary server

### ISSUE THREAD

**Issue by maddie** [holyshawn/overture#5]
When I have primary DNS server set as DNSPod (119.29.29.29:53) and set `EDNSClientSubnetPolicy` to `auto`, I'm getting numerous error saying: (not the exact line but the same meaning):

`DNS result returned nil, maybe timeout`

... which results in extremely slow DNS resolution for almost all websites (including the domestic ones like `baidu.com`). As stated in `README`, DNSPod should support `EDNSClientSubnetPolicy`.

Setting `EDNSClientSubnetPolicy` to `disable` solves this problem.

**Comment by holyshawn** [comment]
#3 has the same problem, maybe it's a bug of dig in debian 8.
There is no such problem in osx.
If this error show again when you normally use overture without dig, please let me know the system and application.

**Comment by holyshawn** [comment]
@maddie Fix this bug in version 1.2.1.

**Comment by maddie** [comment]
Thanks, will test later.

The errors were generated from normal DNS request, not from `dig` command.

The gateway runs on 32-bit Ubuntu 14.04.4 LTS, and it acts as a router for the whole internal network. All DNS lookups are being forwarded from a bind9 daemon to overture, both are running on said gateway.

**Comment by maddie** [comment]
Problem seems to be fixed with version `1.2.1`, closing issue.

Thanks!
